### PR TITLE
Remove name and email from identify custom_attributes object, update …

### PR DESCRIPTION
**Pull request by brennan**
@hankim813 Let me know what you think!

### CODE REVIEW

**Comment by hankim813** [comment]
@brennan hey great job on the PR. I thought more about the impact of this though... and not sure if we want to do this. My reasoning is that even though we shouldn't have been sending semantic traits duplicately under custom_attributes, this is the current prod behavior and I'm afraid a lot of customers would have their reports broken if we stop sending email/name under both top level and inside custom attrs. 

Also, is this change necessary to ship on the client side as well? From the looks of it, we don't even set `custom_attributes` so I'm wondering if this change would be nullified from the client side continuing to treat email/name as both top level and custom_attributes implicitly under the hood? 

If you can confirm that sending `traits.name` and `traits.email` on the client side _only_ updates the proper top level name and email fields inside Intercom UI, I think I'd feel much better shipping this for the server side.

**Comment by brennan** [comment]
Thanks, @hankim813! Just tested, and confirming that passing `traits.name` and `traits.email` on the client only updates the proper top-level name and email fields in Intercom's UI.

**Comment by hankim813** [comment]
@brennan nice! yeah then im okay with shipping this :)

can you add a release commit on top of this? 
- bump `package.json` a patch version
- update `HISTORY.md`
- `$ git commit -m 'Release x.x.x'

Thanks!

**Comment by brennan** [comment]
@hankim813 Cool - just pushed the release commit!

**Pull request merged**
