### PR TITLE
map context.userAgent to last_seen_user_agent EPD-1314

### PR DESCRIPTION
**Pull request by anoonan**
This PR maps `context.userAgent` to `last_seen_user_agent` like we metion in our docs here: https://segment.com/docs/integrations/intercom/#server-side-mobile

**Updates to Test:**
In addition to creating a specific test and fixture for this (identify-last-seen-user-agent.json). I also added a `userAgent` field to fixtures/tests that test how we handle the context object in identify calls:

-identify-collect-context.json
-identify-context.json

I also updated test/helper.js to put `userAgent` inside the context object. It was previously in the traits object. 

Intercom docs on `last_seen_user_agent`: https://developers.intercom.com/reference#create-or-update-user

@tsholmes @ladanazita

### CODE REVIEW

**Comment by hankim813** [comment]
@tsholmes @thehydroimpulse can you guys help noonan with the deploys? What's the deal with the versioned integration/branches?

**Comment by thehydroimpulse** [comment]
ah yeah. versioned integrations are in a weird state right now. I have time this afternoon to go through this.

**Comment by anoonan** [comment]
@thehydroimpulse @tsholmes im going to merge this because I have another fix for this integration that I'm going to work on today. we can deploy both at the time.

**Comment by thehydroimpulse** [comment]
@anoonan are these changes for the versioned integration? If so, you'll need to point to a different branch instead of master.

**Comment by anoonan** [comment]
@thehydroimpulse they are for both versions, I'll do the fix for this on the versioned branch as well today. @hankim813 gave me the low down on how to do that.

**Comment by thehydroimpulse** [comment]
👍

**Pull request merged**
